import { useState, useEffect, useCallback, useRef } from "react";
import { 
  ChevronRight, 
  Folder, 
  FolderOpen,
  FileText, 
  Plus, 
  Search, 
  MoreVertical,
  Save,
  Tag,
  CheckCircle2,
  Zap,
  Trash2,
  Edit,
  Loader2,
  X,
  Bold,
  Italic,
  Heading1,
  Heading2,
  Code,
  List,
  ListOrdered,
  Quote,
  Sparkles,
  BookOpen,
  HelpCircle,
  Link,
  Lightbulb,
  BookMarked,
  Workflow,
  Target,
  GraduationCap,
  Eye,
  EyeOff,
  Brain,
  ListChecks,
  ClipboardList
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
  DropdownMenuSeparator,
} from "@/components/ui/dropdown-menu";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
  DialogDescription,
} from "@/components/ui/dialog";
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from "@/components/ui/tooltip";
import { Separator } from "@/components/ui/separator";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { apiRequest } from "@/lib/queryClient";
import { useToast } from "@/hooks/use-toast";
import { useLocation } from "wouter";
import type { Note, Deck } from "@shared/schema";

interface NoteWithBlocks extends Note {
  blocks?: { id: string; type: string; content: string; order: number }[];
}

function FormatButton({ 
  icon: Icon, 
  label, 
  shortcut, 
  onClick, 
  active = false 
}: { 
  icon: React.ElementType; 
  label: string; 
  shortcut?: string; 
  onClick: () => void;
  active?: boolean;
}) {
  return (
    <Tooltip>
      <TooltipTrigger asChild>
        <Button
          variant={active ? "secondary" : "ghost"}
          size="icon"
          className="h-8 w-8"
          onClick={onClick}
          data-testid={`button-format-${label.toLowerCase().replace(/\s+/g, '-')}`}
        >
          <Icon className="h-4 w-4" />
        </Button>
      </TooltipTrigger>
      <TooltipContent>
        <p>{label}{shortcut && <span className="ml-2 text-muted-foreground">{shortcut}</span>}</p>
      </TooltipContent>
    </Tooltip>
  );
}

export default function Notes() {
  const [selectedNoteId, setSelectedNoteId] = useState<string | null>(null);
  const [noteTitle, setNoteTitle] = useState("");
  const [noteContent, setNoteContent] = useState("");
  const [noteSubject, setNoteSubject] = useState("");
  const [noteTags, setNoteTags] = useState<string[]>([]);
  const [isSaved, setIsSaved] = useState(true);
  const [searchQuery, setSearchQuery] = useState("");
  const [showNewNoteDialog, setShowNewNoteDialog] = useState(false);
  const [newNoteTitle, setNewNoteTitle] = useState("");
  const [newNoteSubject, setNewNoteSubject] = useState("");
  const [tagInput, setTagInput] = useState("");
  const [expandedSubjects, setExpandedSubjects] = useState<Set<string>>(new Set());
  const [showFlashcardDialog, setShowFlashcardDialog] = useState(false);
  const [showQuizDialog, setShowQuizDialog] = useState(false);
  const [selectedText, setSelectedText] = useState("");
  const [flashcardFront, setFlashcardFront] = useState("");
  const [flashcardBack, setFlashcardBack] = useState("");
  const [selectedDeckId, setSelectedDeckId] = useState<string>("");
  const [quizQuestion, setQuizQuestion] = useState("");
  const [quizOptions, setQuizOptions] = useState(["", "", "", ""]);
  const [correctOptionIndex, setCorrectOptionIndex] = useState(0);
  const [selectedQuizId, setSelectedQuizId] = useState<string>("");
  const [quizExplanation, setQuizExplanation] = useState("");
  const [recallMode, setRecallMode] = useState(false);
  const [selectedNoteType, setSelectedNoteType] = useState<string>("general");
  const [showExamPrompt, setShowExamPrompt] = useState(false);
  const [examPromptType, setExamPromptType] = useState<string>("SAQ");
  const [examMarks, setExamMarks] = useState<number>(4);
  const [keyTermsInput, setKeyTermsInput] = useState("");
  const [showAutoGenerateDialog, setShowAutoGenerateDialog] = useState(false);
  const [autoGenerateType, setAutoGenerateType] = useState<"quiz" | "flashcards">("quiz");
  const [isGenerating, setIsGenerating] = useState(false);
  const textareaRef = useRef<HTMLTextAreaElement>(null);
  
  const [, setLocation] = useLocation();
  const queryClient = useQueryClient();
  const { toast } = useToast();

  const { data: notes = [], isLoading } = useQuery<Note[]>({
    queryKey: ["/api/notes"],
  });

  const { data: selectedNote } = useQuery<NoteWithBlocks>({
    queryKey: ["/api/notes", selectedNoteId],
    enabled: !!selectedNoteId,
  });

  const { data: decks = [] } = useQuery<Deck[]>({
    queryKey: ["/api/flashcard-decks"],
  });

  const { data: quizzes = [] } = useQuery<{ id: string; title: string; subject: string | null }[]>({
    queryKey: ["/api/quizzes"],
  });

  useEffect(() => {
    if (selectedNote) {
      setNoteTitle(selectedNote.title);
      setNoteSubject(selectedNote.subject || "");
      setNoteTags(selectedNote.tags || []);
      const content = selectedNote.blocks?.map(b => b.content).join("\n\n") || "";
      setNoteContent(content);
      setIsSaved(true);
    }
  }, [selectedNote]);

  useEffect(() => {
    if (notes.length > 0 && !selectedNoteId) {
      setSelectedNoteId(notes[0].id);
    }
  }, [notes, selectedNoteId]);

  const createNoteMutation = useMutation({
    mutationFn: async (data: { title: string; subject?: string; tags?: string[] }) => {
      const res = await apiRequest("POST", "/api/notes", {
        ...data,
        blocks: [{ type: "markdown", content: "" }],
      });
      return res.json();
    },
    onSuccess: (newNote) => {
      queryClient.invalidateQueries({ queryKey: ["/api/notes"] });
      setSelectedNoteId(newNote.id);
      setShowNewNoteDialog(false);
      setNewNoteTitle("");
      setNewNoteSubject("");
      toast({ title: "Note created", description: "Your new note is ready." });
    },
    onError: () => {
      toast({ title: "Error", description: "Failed to create note", variant: "destructive" });
    },
  });

  const lastSavedContentRef = useRef<string>("");
  const lastSavedTitleRef = useRef<string>("");

  const updateNoteMutation = useMutation({
    mutationFn: async ({ id, data, content }: { id: string; data: Partial<Note>; content?: string }) => {
      const payload: any = { ...data };
      if (content !== undefined) {
        payload.blocks = [{ type: "markdown", content }];
      }
      const res = await apiRequest("PATCH", `/api/notes/${id}`, payload);
      return { response: await res.json(), savedContent: content, savedTitle: data.title };
    },
    onSuccess: (result) => {
      queryClient.invalidateQueries({ queryKey: ["/api/notes"] });
      queryClient.invalidateQueries({ queryKey: ["/api/notes", selectedNoteId] });
      lastSavedContentRef.current = result.savedContent || "";
      lastSavedTitleRef.current = result.savedTitle || "";
      if (noteContent === result.savedContent && noteTitle === result.savedTitle) {
        setIsSaved(true);
      }
    },
    onError: () => {
      toast({ title: "Error", description: "Failed to save note", variant: "destructive" });
    },
  });

  const deleteNoteMutation = useMutation({
    mutationFn: async (id: string) => {
      await apiRequest("DELETE", `/api/notes/${id}`);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/notes"] });
      if (selectedNoteId === notes.find(n => n.id === selectedNoteId)?.id) {
        const remaining = notes.filter(n => n.id !== selectedNoteId);
        setSelectedNoteId(remaining[0]?.id || null);
      }
      toast({ title: "Note deleted" });
    },
    onError: () => {
      toast({ title: "Error", description: "Failed to delete note", variant: "destructive" });
    },
  });

  const createFlashcardMutation = useMutation({
    mutationFn: async (data: { deckId: string; front: string; back: string }) => {
      const res = await apiRequest("POST", `/api/flashcard-decks/${data.deckId}/cards`, {
        front: data.front,
        back: data.back,
        type: "basic",
      });
      return res.json();
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/flashcard-decks"] });
      setShowFlashcardDialog(false);
      setFlashcardFront("");
      setFlashcardBack("");
      setSelectedDeckId("");
      toast({ 
        title: "Flashcard created", 
        description: "Your flashcard has been added to the deck.",
      });
    },
    onError: () => {
      toast({ title: "Error", description: "Failed to create flashcard", variant: "destructive" });
    },
  });

  const createQuizQuestionMutation = useMutation({
    mutationFn: async (data: { 
      quizId: string; 
      question: string; 
      options: { text: string; isCorrect: boolean }[];
      explanation: string;
    }) => {
      const res = await apiRequest("POST", `/api/quizzes/${data.quizId}/questions`, {
        question: data.question,
        type: "mcq",
        difficulty: 3,
        marks: 1,
        explanation: data.explanation || "Review this concept in your notes.",
        options: data.options,
      });
      return res.json();
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/quizzes"] });
      setShowQuizDialog(false);
      setQuizQuestion("");
      setQuizOptions(["", "", "", ""]);
      setCorrectOptionIndex(0);
      setSelectedQuizId("");
      setQuizExplanation("");
      toast({ 
        title: "Quiz question created", 
        description: "Your question has been added to the quiz.",
      });
    },
    onError: () => {
      toast({ title: "Error", description: "Failed to create quiz question", variant: "destructive" });
    },
  });

  // Auto-generate quiz from entire note
  const generateQuizMutation = useMutation({
    mutationFn: async ({ noteId, questionCount }: { noteId: string; questionCount?: number }) => {
      const res = await apiRequest("POST", `/api/notes/${noteId}/generate-quiz`, { questionCount });
      return res.json();
    },
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: ["/api/quizzes"] });
      setShowAutoGenerateDialog(false);
      setIsGenerating(false);
      toast({ 
        title: "Quiz Generated!", 
        description: data.message,
      });
    },
    onError: () => {
      setIsGenerating(false);
      toast({ title: "Error", description: "Failed to generate quiz from note", variant: "destructive" });
    },
  });

  // Auto-generate flashcards from entire note
  const generateFlashcardsMutation = useMutation({
    mutationFn: async ({ noteId, deckId }: { noteId: string; deckId: string }) => {
      const res = await apiRequest("POST", `/api/notes/${noteId}/generate-flashcards`, { deckId });
      return res.json();
    },
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: ["/api/flashcard-decks"] });
      queryClient.invalidateQueries({ queryKey: ["/api/decks"] });
      setShowAutoGenerateDialog(false);
      setIsGenerating(false);
      toast({ 
        title: "Flashcards Generated!", 
        description: data.message,
      });
    },
    onError: () => {
      setIsGenerating(false);
      toast({ title: "Error", description: "Failed to generate flashcards from note", variant: "destructive" });
    },
  });

  const handleAutoGenerate = () => {
    if (!selectedNoteId) return;
    setIsGenerating(true);
    
    if (autoGenerateType === "quiz") {
      generateQuizMutation.mutate({ noteId: selectedNoteId, questionCount: 5 });
    } else {
      if (!selectedDeckId) {
        setIsGenerating(false);
        toast({ title: "Select a deck", description: "Please select a deck for the flashcards", variant: "destructive" });
        return;
      }
      generateFlashcardsMutation.mutate({ noteId: selectedNoteId, deckId: selectedDeckId });
    }
  };

  // Insert exam prompt annotation
  const insertExamPrompt = () => {
    const annotation = `\n\n> **${examPromptType}** (${examMarks} marks)\n`;
    setNoteContent(noteContent + annotation);
    setIsSaved(false);
    setShowExamPrompt(false);
    toast({ title: "Exam prompt added", description: `Added ${examPromptType} annotation (${examMarks} marks)` });
  };

  // Get content for recall mode (hide key terms)
  const getRecallContent = (content: string): string => {
    if (!recallMode || !keyTermsInput) return content;
    
    const terms = keyTermsInput.split(',').map(t => t.trim()).filter(Boolean);
    let maskedContent = content;
    
    for (const term of terms) {
      const regex = new RegExp(`\\b${term}\\b`, 'gi');
      maskedContent = maskedContent.replace(regex, '▓'.repeat(term.length));
    }
    
    return maskedContent;
  };

  const handleSave = useCallback(() => {
    if (!selectedNoteId || updateNoteMutation.isPending) return;
    updateNoteMutation.mutate({
      id: selectedNoteId,
      data: {
        title: noteTitle,
        subject: noteSubject || undefined,
        tags: noteTags.length > 0 ? noteTags : undefined,
      },
      content: noteContent,
    });
  }, [selectedNoteId, noteTitle, noteSubject, noteTags, noteContent, updateNoteMutation]);

  useEffect(() => {
    if (!isSaved && selectedNoteId && !updateNoteMutation.isPending) {
      const timer = setTimeout(() => {
        handleSave();
      }, 1500);
      return () => clearTimeout(timer);
    }
  }, [isSaved, noteTitle, noteContent, noteSubject, noteTags, handleSave, selectedNoteId, updateNoteMutation.isPending]);

  const insertFormat = (before: string, after: string = "") => {
    const textarea = textareaRef.current;
    if (!textarea) return;
    
    const start = textarea.selectionStart;
    const end = textarea.selectionEnd;
    const selected = noteContent.substring(start, end);
    const newText = noteContent.substring(0, start) + before + selected + after + noteContent.substring(end);
    
    setNoteContent(newText);
    setIsSaved(false);
    
    setTimeout(() => {
      textarea.focus();
      textarea.setSelectionRange(start + before.length, end + before.length);
    }, 0);
  };

  const insertAtLineStart = (prefix: string) => {
    const textarea = textareaRef.current;
    if (!textarea) return;
    
    const start = textarea.selectionStart;
    const lineStart = noteContent.lastIndexOf('\n', start - 1) + 1;
    const newText = noteContent.substring(0, lineStart) + prefix + noteContent.substring(lineStart);
    
    setNoteContent(newText);
    setIsSaved(false);
    
    setTimeout(() => {
      textarea.focus();
      textarea.setSelectionRange(start + prefix.length, start + prefix.length);
    }, 0);
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.ctrlKey || e.metaKey) {
      switch (e.key.toLowerCase()) {
        case 'b':
          e.preventDefault();
          insertFormat('**', '**');
          break;
        case 'i':
          e.preventDefault();
          insertFormat('*', '*');
          break;
        case 's':
          e.preventDefault();
          handleSave();
          break;
      }
    }
  };

  const getSelectedText = () => {
    const textarea = textareaRef.current;
    if (!textarea) return "";
    return noteContent.substring(textarea.selectionStart, textarea.selectionEnd);
  };

  const openFlashcardDialog = () => {
    const selected = getSelectedText();
    setSelectedText(selected);
    setFlashcardFront(selected || noteTitle);
    setFlashcardBack("");
    setShowFlashcardDialog(true);
  };

  const openQuizDialog = () => {
    const selected = getSelectedText();
    setSelectedText(selected);
    setQuizQuestion(selected || "");
    setQuizOptions(["", "", "", ""]);
    setCorrectOptionIndex(0);
    setShowQuizDialog(true);
  };

  const askInsightScout = () => {
    const selected = getSelectedText() || noteTitle;
    const query = encodeURIComponent(`Explain: ${selected}`);
    setLocation(`/research?query=${query}`);
  };

  const addTag = () => {
    if (tagInput.trim() && !noteTags.includes(tagInput.trim())) {
      setNoteTags([...noteTags, tagInput.trim()]);
      setTagInput("");
      setIsSaved(false);
    }
  };

  const removeTag = (tag: string) => {
    setNoteTags(noteTags.filter(t => t !== tag));
    setIsSaved(false);
  };

  const toggleSubject = (subject: string) => {
    const newExpanded = new Set(expandedSubjects);
    if (newExpanded.has(subject)) {
      newExpanded.delete(subject);
    } else {
      newExpanded.add(subject);
    }
    setExpandedSubjects(newExpanded);
  };

  const groupedNotes = notes.reduce((acc, note) => {
    const subject = note.subject || "Uncategorized";
    if (!acc[subject]) acc[subject] = [];
    acc[subject].push(note);
    return acc;
  }, {} as Record<string, Note[]>);

  const filteredGroups = Object.entries(groupedNotes).reduce((acc, [subject, subjectNotes]) => {
    const filtered = subjectNotes.filter(note =>
      note.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
      note.tags?.some(tag => tag.toLowerCase().includes(searchQuery.toLowerCase()))
    );
    if (filtered.length > 0) {
      acc[subject] = filtered;
    }
    return acc;
  }, {} as Record<string, Note[]>);

  useEffect(() => {
    if (Object.keys(filteredGroups).length > 0 && expandedSubjects.size === 0) {
      setExpandedSubjects(new Set(Object.keys(filteredGroups)));
    }
  }, [filteredGroups, expandedSubjects.size]);

  if (isLoading) {
    return (
      <div className="flex h-full items-center justify-center bg-slate-50 dark:bg-slate-950">
        <Loader2 className="h-8 w-8 animate-spin text-blue-500" />
      </div>
    );
  }

  return (
    <div className="flex h-full bg-slate-50 dark:bg-slate-950">
      <div className="w-72 border-r border-blue-200 dark:border-blue-900 flex flex-col bg-white dark:bg-slate-900 shadow-sm">
        <div className="p-4 border-b border-blue-100 dark:border-blue-900 space-y-3 bg-gradient-to-b from-blue-50 to-white dark:from-blue-950 dark:to-slate-900">
          <div className="flex items-center gap-2 mb-2">
            <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-blue-400 to-blue-600 flex items-center justify-center">
              <FileText className="h-5 w-5 text-white" />
            </div>
            <h2 className="text-lg font-bold bg-gradient-to-r from-blue-600 to-blue-700 dark:from-blue-400 dark:to-blue-300 bg-clip-text text-transparent">
              Notes
            </h2>
          </div>
          <div className="relative">
            <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-blue-400" />
            <Input
              placeholder="Search notes..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="pl-9 bg-blue-50 dark:bg-slate-800 border-blue-200 dark:border-blue-800 focus-visible:ring-blue-500 focus-visible:border-blue-400"
              data-testid="input-search-notes"
            />
          </div>
          <Button 
            className="w-full bg-gradient-to-r from-blue-500 to-blue-600 hover:from-blue-600 hover:to-blue-700 text-white" 
            size="sm" 
            onClick={() => setShowNewNoteDialog(true)}
            data-testid="button-new-note"
          >
            <Plus className="h-4 w-4 mr-2" />
            New Note
          </Button>
        </div>

        <div className="flex-1 overflow-auto p-2">
          {Object.keys(filteredGroups).length === 0 ? (
            <div className="text-center py-8 text-muted-foreground">
              <FileText className="h-8 w-8 mx-auto mb-2 opacity-50" />
              <p className="text-sm">No notes found</p>
              <p className="text-xs mt-1">Create your first note!</p>
            </div>
          ) : (
            Object.entries(filteredGroups).map(([subject, subjectNotes]) => {
              const isExpanded = expandedSubjects.has(subject);
              return (
                <div key={subject} className="mb-2">
                  <Button
                    variant="ghost"
                    size="sm"
                    className="w-full justify-start gap-2 hover-elevate group"
                    onClick={() => toggleSubject(subject)}
                    data-testid={`button-subject-${subject}`}
                  >
                    <div className={`transition-transform duration-200 ${isExpanded ? 'rotate-90' : ''}`}>
                      <ChevronRight className="h-4 w-4 text-blue-500" />
                    </div>
                    {isExpanded ? (
                      <FolderOpen className="h-4 w-4 text-blue-400" />
                    ) : (
                      <Folder className="h-4 w-4 text-blue-400" />
                    )}
                    <span className="flex-1 text-left font-medium text-sm">{subject}</span>
                    <span className="text-xs text-muted-foreground">{subjectNotes.length}</span>
                  </Button>
                  {isExpanded && (
                    <div className="ml-4 border-l-2 border-blue-200 dark:border-blue-800 pl-2 space-y-1">
                      {subjectNotes.map((note) => {
                        const isSelected = selectedNoteId === note.id;
                        return (
                          <Button
                            key={note.id}
                            variant={isSelected ? "secondary" : "ghost"}
                            size="sm"
                            className={`w-full justify-start gap-2 group ${
                              isSelected
                                ? "bg-blue-100 dark:bg-blue-950 text-blue-900 dark:text-blue-100"
                                : ""
                            }`}
                            onClick={() => setSelectedNoteId(note.id)}
                            data-testid={`button-note-${note.id}`}
                          >
                            <FileText className={`h-4 w-4 ${isSelected ? "text-blue-600" : "text-slate-400"}`} />
                            <span className="flex-1 text-left truncate text-sm">{note.title}</span>
                            {isSelected && <CheckCircle2 className="h-4 w-4 text-blue-600 flex-shrink-0" />}
                          </Button>
                        );
                      })}
                    </div>
                  )}
                </div>
              );
            })
          )}
        </div>
      </div>

      <div className="flex-1 flex flex-col bg-white dark:bg-slate-900">
        {selectedNoteId ? (
          <>
            <div className="border-b border-blue-200 dark:border-blue-900 px-6 py-4 flex items-center justify-between gap-4 bg-gradient-to-r from-blue-50 to-indigo-50 dark:from-slate-900 dark:to-slate-800">
              <div className="flex-1">
                <Input
                  value={noteTitle}
                  onChange={(e) => {
                    setNoteTitle(e.target.value);
                    setIsSaved(false);
                  }}
                  className="text-2xl font-bold border-0 bg-transparent focus-visible:ring-0 px-0 focus-visible:outline-none"
                  placeholder="Untitled Note"
                  data-testid="input-note-title"
                />
                <Input
                  value={noteSubject}
                  onChange={(e) => {
                    setNoteSubject(e.target.value);
                    setIsSaved(false);
                  }}
                  className="text-sm text-muted-foreground border-0 bg-transparent focus-visible:ring-0 px-0 mt-1"
                  placeholder="Subject (e.g., Computer Science)"
                  data-testid="input-note-subject"
                />
              </div>

              <div className="flex items-center gap-3 ml-4">
                {updateNoteMutation.isPending ? (
                  <Badge className="bg-blue-100 dark:bg-blue-950 text-blue-700 dark:text-blue-300 gap-1 border-0">
                    <Loader2 className="h-3 w-3 animate-spin" />
                    Saving...
                  </Badge>
                ) : isSaved ? (
                  <Badge variant="secondary" className="bg-green-100 dark:bg-green-950 text-green-700 dark:text-green-300 gap-1 border-0">
                    <CheckCircle2 className="h-3 w-3" />
                    Saved
                  </Badge>
                ) : (
                  <Badge className="bg-amber-100 dark:bg-amber-950 text-amber-700 dark:text-amber-300 gap-1 border-0 animate-pulse">
                    <Zap className="h-3 w-3" />
                    Unsaved
                  </Badge>
                )}

                <Button
                  variant="outline"
                  size="sm"
                  onClick={handleSave}
                  disabled={isSaved || updateNoteMutation.isPending}
                  data-testid="button-save-note"
                >
                  <Save className="h-4 w-4 mr-2" />
                  Save
                </Button>

                <DropdownMenu>
                  <DropdownMenuTrigger asChild>
                    <Button variant="ghost" size="icon" data-testid="button-note-options">
                      <MoreVertical className="h-5 w-5" />
                    </Button>
                  </DropdownMenuTrigger>
                  <DropdownMenuContent align="end" className="w-48">
                    <DropdownMenuItem className="gap-2">
                      <Edit className="h-4 w-4" />
                      Rename
                    </DropdownMenuItem>
                    <DropdownMenuSeparator />
                    <DropdownMenuItem 
                      className="text-destructive gap-2"
                      onClick={() => selectedNoteId && deleteNoteMutation.mutate(selectedNoteId)}
                    >
                      <Trash2 className="h-4 w-4" />
                      Delete Note
                    </DropdownMenuItem>
                  </DropdownMenuContent>
                </DropdownMenu>
              </div>
            </div>

            <div className="px-6 py-3 border-b border-blue-100 dark:border-blue-900 flex items-center gap-2 flex-wrap">
              <Tag className="h-4 w-4 text-blue-500" />
              {noteTags.map((tag) => (
                <Badge
                  key={tag}
                  variant="secondary"
                  className="gap-1 bg-blue-100 dark:bg-blue-900 text-blue-700 dark:text-blue-300"
                >
                  {tag}
                  <button onClick={() => removeTag(tag)} className="ml-1 hover:text-red-500">
                    <X className="h-3 w-3" />
                  </button>
                </Badge>
              ))}
              <div className="flex items-center gap-1">
                <Input
                  value={tagInput}
                  onChange={(e) => setTagInput(e.target.value)}
                  onKeyDown={(e) => e.key === "Enter" && addTag()}
                  placeholder="Add tag..."
                  className="h-7 w-24 text-xs"
                  data-testid="input-add-tag"
                />
                <Button size="sm" variant="ghost" onClick={addTag} className="h-7 px-2">
                  <Plus className="h-3 w-3" />
                </Button>
              </div>
            </div>

            <div className="px-6 py-2 border-b border-blue-100 dark:border-blue-900 flex items-center gap-1 flex-wrap bg-slate-50 dark:bg-slate-800/50">
              <div className="flex items-center gap-1">
                <FormatButton icon={Bold} label="Bold" shortcut="Ctrl+B" onClick={() => insertFormat('**', '**')} />
                <FormatButton icon={Italic} label="Italic" shortcut="Ctrl+I" onClick={() => insertFormat('*', '*')} />
              </div>
              <Separator orientation="vertical" className="h-6 mx-1" />
              <div className="flex items-center gap-1">
                <FormatButton icon={Heading1} label="Heading 1" onClick={() => insertAtLineStart('# ')} />
                <FormatButton icon={Heading2} label="Heading 2" onClick={() => insertAtLineStart('## ')} />
              </div>
              <Separator orientation="vertical" className="h-6 mx-1" />
              <div className="flex items-center gap-1">
                <FormatButton icon={List} label="Bullet List" onClick={() => insertAtLineStart('- ')} />
                <FormatButton icon={ListOrdered} label="Numbered List" onClick={() => insertAtLineStart('1. ')} />
                <FormatButton icon={Quote} label="Quote" onClick={() => insertAtLineStart('> ')} />
              </div>
              <Separator orientation="vertical" className="h-6 mx-1" />
              <div className="flex items-center gap-1">
                <FormatButton icon={Code} label="Code Block" onClick={() => insertFormat('```\n', '\n```')} />
                <FormatButton icon={Link} label="Link" onClick={() => insertFormat('[', '](url)')} />
              </div>
              
              <div className="flex-1" />
              
              <div className="flex items-center gap-1">
                <Tooltip>
                  <TooltipTrigger asChild>
                    <Button
                      variant="outline"
                      size="sm"
                      className="gap-2 bg-emerald-50 dark:bg-emerald-950 border-emerald-200 dark:border-emerald-800 text-emerald-700 dark:text-emerald-300 hover:bg-emerald-100 dark:hover:bg-emerald-900"
                      onClick={openFlashcardDialog}
                      data-testid="button-convert-flashcard"
                    >
                      <BookOpen className="h-4 w-4" />
                      <span className="hidden sm:inline">Flashcard</span>
                    </Button>
                  </TooltipTrigger>
                  <TooltipContent>Convert selection to flashcard</TooltipContent>
                </Tooltip>
                
                <Tooltip>
                  <TooltipTrigger asChild>
                    <Button
                      variant="outline"
                      size="sm"
                      className="gap-2 bg-fuchsia-50 dark:bg-fuchsia-950 border-fuchsia-200 dark:border-fuchsia-800 text-fuchsia-700 dark:text-fuchsia-300 hover:bg-fuchsia-100 dark:hover:bg-fuchsia-900"
                      onClick={openQuizDialog}
                      data-testid="button-convert-quiz"
                    >
                      <HelpCircle className="h-4 w-4" />
                      <span className="hidden sm:inline">Quiz</span>
                    </Button>
                  </TooltipTrigger>
                  <TooltipContent>Convert selection to quiz question</TooltipContent>
                </Tooltip>
                
                <Tooltip>
                  <TooltipTrigger asChild>
                    <Button
                      variant="outline"
                      size="sm"
                      className="gap-2 bg-amber-50 dark:bg-amber-950 border-amber-200 dark:border-amber-800 text-amber-700 dark:text-amber-300 hover:bg-amber-100 dark:hover:bg-amber-900"
                      onClick={askInsightScout}
                      data-testid="button-ask-insight-scout"
                    >
                      <Sparkles className="h-4 w-4" />
                      <span className="hidden sm:inline">Ask AI</span>
                    </Button>
                  </TooltipTrigger>
                  <TooltipContent>Research with Insight Scout</TooltipContent>
                </Tooltip>
              </div>
            </div>

            {/* Smart Note Types & Learning Tools Bar */}
            <div className="px-6 py-2 border-b border-blue-100 dark:border-blue-900 flex items-center gap-3 flex-wrap bg-gradient-to-r from-teal-50/50 to-cyan-50/50 dark:from-teal-950/30 dark:to-cyan-950/30">
              {/* Note Type Selector */}
              <div className="flex items-center gap-2">
                <span className="text-xs font-medium text-muted-foreground">Type:</span>
                <Select value={selectedNoteType} onValueChange={setSelectedNoteType}>
                  <SelectTrigger className="h-7 w-32 text-xs" data-testid="select-note-type">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="general">
                      <div className="flex items-center gap-2">
                        <FileText className="h-3 w-3" /> General
                      </div>
                    </SelectItem>
                    <SelectItem value="concept">
                      <div className="flex items-center gap-2">
                        <Lightbulb className="h-3 w-3 text-yellow-500" /> Concept
                      </div>
                    </SelectItem>
                    <SelectItem value="definition">
                      <div className="flex items-center gap-2">
                        <BookMarked className="h-3 w-3 text-blue-500" /> Definition
                      </div>
                    </SelectItem>
                    <SelectItem value="process">
                      <div className="flex items-center gap-2">
                        <Workflow className="h-3 w-3 text-green-500" /> Process
                      </div>
                    </SelectItem>
                    <SelectItem value="example">
                      <div className="flex items-center gap-2">
                        <Target className="h-3 w-3 text-orange-500" /> Example
                      </div>
                    </SelectItem>
                    <SelectItem value="exam_tip">
                      <div className="flex items-center gap-2">
                        <GraduationCap className="h-3 w-3 text-purple-500" /> Exam Tip
                      </div>
                    </SelectItem>
                  </SelectContent>
                </Select>
              </div>

              <Separator orientation="vertical" className="h-6" />

              {/* Exam Prompt Button */}
              <Tooltip>
                <TooltipTrigger asChild>
                  <Button
                    variant="outline"
                    size="sm"
                    className="h-7 gap-1.5 text-xs bg-red-50 dark:bg-red-950 border-red-200 dark:border-red-800 text-red-700 dark:text-red-300"
                    onClick={() => setShowExamPrompt(!showExamPrompt)}
                    data-testid="button-add-exam-prompt"
                  >
                    <ClipboardList className="h-3.5 w-3.5" />
                    Exam Prompt
                  </Button>
                </TooltipTrigger>
                <TooltipContent>Add exam question annotation</TooltipContent>
              </Tooltip>

              {showExamPrompt && (
                <div className="flex items-center gap-2 bg-white dark:bg-slate-900 border rounded-lg px-2 py-1">
                  <Select value={examPromptType} onValueChange={setExamPromptType}>
                    <SelectTrigger className="h-6 w-20 text-xs">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="SAQ">SAQ</SelectItem>
                      <SelectItem value="MCQ">MCQ</SelectItem>
                      <SelectItem value="LAQ">LAQ</SelectItem>
                      <SelectItem value="Essay">Essay</SelectItem>
                    </SelectContent>
                  </Select>
                  <Input
                    type="number"
                    value={examMarks}
                    onChange={(e) => setExamMarks(parseInt(e.target.value) || 1)}
                    className="h-6 w-14 text-xs"
                    min={1}
                    max={20}
                    placeholder="Marks"
                  />
                  <span className="text-xs text-muted-foreground">marks</span>
                  <Button size="sm" className="h-6 px-2 text-xs" onClick={insertExamPrompt}>
                    Add
                  </Button>
                </div>
              )}

              <div className="flex-1" />

              {/* Recall Mode */}
              <div className="flex items-center gap-2">
                <Tooltip>
                  <TooltipTrigger asChild>
                    <div className="flex items-center gap-2">
                      <Brain className="h-4 w-4 text-purple-500" />
                      <span className="text-xs font-medium">Recall Mode</span>
                      <Switch
                        checked={recallMode}
                        onCheckedChange={setRecallMode}
                        data-testid="switch-recall-mode"
                      />
                    </div>
                  </TooltipTrigger>
                  <TooltipContent>Hide key terms to test your memory</TooltipContent>
                </Tooltip>
              </div>

              {recallMode && (
                <Input
                  value={keyTermsInput}
                  onChange={(e) => setKeyTermsInput(e.target.value)}
                  placeholder="Key terms (comma-separated)..."
                  className="h-7 w-48 text-xs"
                  data-testid="input-key-terms"
                />
              )}

              <Separator orientation="vertical" className="h-6" />

              {/* Auto-Generate Buttons */}
              <Tooltip>
                <TooltipTrigger asChild>
                  <Button
                    variant="outline"
                    size="sm"
                    className="h-7 gap-1.5 text-xs bg-teal-50 dark:bg-teal-950 border-teal-200 dark:border-teal-800 text-teal-700 dark:text-teal-300"
                    onClick={() => {
                      setAutoGenerateType("quiz");
                      setShowAutoGenerateDialog(true);
                    }}
                    data-testid="button-auto-generate-quiz"
                  >
                    <ListChecks className="h-3.5 w-3.5" />
                    Generate Quiz
                  </Button>
                </TooltipTrigger>
                <TooltipContent>Auto-generate quiz from this note</TooltipContent>
              </Tooltip>

              <Tooltip>
                <TooltipTrigger asChild>
                  <Button
                    variant="outline"
                    size="sm"
                    className="h-7 gap-1.5 text-xs bg-cyan-50 dark:bg-cyan-950 border-cyan-200 dark:border-cyan-800 text-cyan-700 dark:text-cyan-300"
                    onClick={() => {
                      setAutoGenerateType("flashcards");
                      setShowAutoGenerateDialog(true);
                    }}
                    data-testid="button-auto-generate-flashcards"
                  >
                    <Zap className="h-3.5 w-3.5" />
                    Generate Cards
                  </Button>
                </TooltipTrigger>
                <TooltipContent>Auto-generate flashcards from this note</TooltipContent>
              </Tooltip>
            </div>

            <div className="flex-1 p-8 overflow-auto">
              <div className="max-w-4xl mx-auto">
                {recallMode && keyTermsInput ? (
                  <div className="space-y-4">
                    <div className="bg-purple-50 dark:bg-purple-950/50 border border-purple-200 dark:border-purple-800 rounded-lg p-4">
                      <div className="flex items-center gap-2 mb-2">
                        <Brain className="h-5 w-5 text-purple-600" />
                        <span className="font-medium text-purple-700 dark:text-purple-300">Recall Mode Active</span>
                      </div>
                      <p className="text-sm text-purple-600 dark:text-purple-400">
                        Key terms are hidden. Try to recall them before revealing!
                      </p>
                    </div>
                    <div className="font-mono text-base leading-relaxed whitespace-pre-wrap">
                      {getRecallContent(noteContent)}
                    </div>
                    <Button 
                      variant="outline" 
                      onClick={() => setRecallMode(false)}
                      className="gap-2"
                    >
                      <Eye className="h-4 w-4" />
                      Reveal All Terms
                    </Button>
                  </div>
                ) : (
                  <Textarea
                    ref={textareaRef}
                    value={noteContent}
                    onChange={(e) => {
                      setNoteContent(e.target.value);
                      setIsSaved(false);
                    }}
                    onKeyDown={handleKeyDown}
                    className="min-h-[500px] resize-none border-0 focus-visible:ring-0 font-mono text-base leading-relaxed bg-transparent focus-visible:outline-none"
                    placeholder="Start typing your notes...

Use the formatting toolbar above or keyboard shortcuts:
• Ctrl+B for **bold**
• Ctrl+I for *italic*
• Ctrl+S to save

Markdown formatting is supported:
# Heading 1
## Heading 2
- Bullet list
1. Numbered list
> Blockquote
```code block```"
                    data-testid="textarea-note-content"
                  />
                )}
              </div>
            </div>
          </>
        ) : (
          <div className="flex-1 flex items-center justify-center">
            <Card className="p-8 text-center max-w-md">
              <FileText className="h-16 w-16 mx-auto mb-4 text-blue-400 opacity-50" />
              <h3 className="text-xl font-semibold mb-2">No Note Selected</h3>
              <p className="text-muted-foreground mb-4">
                Select a note from the sidebar or create a new one to get started.
              </p>
              <Button onClick={() => setShowNewNoteDialog(true)} data-testid="button-create-first-note">
                <Plus className="h-4 w-4 mr-2" />
                Create Note
              </Button>
            </Card>
          </div>
        )}
      </div>

      <Dialog open={showNewNoteDialog} onOpenChange={setShowNewNoteDialog}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Create New Note</DialogTitle>
          </DialogHeader>
          <div className="space-y-4 py-4">
            <div className="space-y-2">
              <label className="text-sm font-medium">Title</label>
              <Input
                value={newNoteTitle}
                onChange={(e) => setNewNoteTitle(e.target.value)}
                placeholder="Enter note title..."
                data-testid="input-new-note-title"
              />
            </div>
            <div className="space-y-2">
              <label className="text-sm font-medium">Subject (optional)</label>
              <Input
                value={newNoteSubject}
                onChange={(e) => setNewNoteSubject(e.target.value)}
                placeholder="e.g., Computer Science, Mathematics..."
                data-testid="input-new-note-subject"
              />
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowNewNoteDialog(false)}>
              Cancel
            </Button>
            <Button
              onClick={() => createNoteMutation.mutate({
                title: newNoteTitle || "Untitled Note",
                subject: newNoteSubject || undefined,
              })}
              disabled={createNoteMutation.isPending}
              data-testid="button-confirm-create-note"
            >
              {createNoteMutation.isPending ? (
                <Loader2 className="h-4 w-4 mr-2 animate-spin" />
              ) : (
                <Plus className="h-4 w-4 mr-2" />
              )}
              Create Note
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      <Dialog open={showFlashcardDialog} onOpenChange={setShowFlashcardDialog}>
        <DialogContent className="max-w-lg">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <BookOpen className="h-5 w-5 text-emerald-600" />
              Create Flashcard from Note
            </DialogTitle>
            <DialogDescription>
              Convert your note content into a flashcard for spaced repetition learning.
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4 py-4">
            <div className="space-y-2">
              <label className="text-sm font-medium">Select Deck</label>
              <select
                value={selectedDeckId}
                onChange={(e) => setSelectedDeckId(e.target.value)}
                className="w-full h-10 px-3 rounded-md border border-input bg-background text-sm"
                data-testid="select-flashcard-deck"
              >
                <option value="">Choose a deck...</option>
                {decks.map((deck) => (
                  <option key={deck.id} value={deck.id}>{deck.title}</option>
                ))}
              </select>
            </div>
            <div className="space-y-2">
              <label className="text-sm font-medium">Front (Question/Term)</label>
              <Textarea
                value={flashcardFront}
                onChange={(e) => setFlashcardFront(e.target.value)}
                placeholder="What do you want to remember?"
                className="min-h-[80px]"
                data-testid="input-flashcard-front"
              />
            </div>
            <div className="space-y-2">
              <label className="text-sm font-medium">Back (Answer/Definition)</label>
              <Textarea
                value={flashcardBack}
                onChange={(e) => setFlashcardBack(e.target.value)}
                placeholder="The answer or explanation..."
                className="min-h-[80px]"
                data-testid="input-flashcard-back"
              />
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowFlashcardDialog(false)}>
              Cancel
            </Button>
            <Button
              onClick={() => createFlashcardMutation.mutate({
                deckId: selectedDeckId,
                front: flashcardFront,
                back: flashcardBack,
              })}
              disabled={!selectedDeckId || !flashcardFront || !flashcardBack || createFlashcardMutation.isPending}
              className="bg-emerald-600 hover:bg-emerald-700"
              data-testid="button-confirm-create-flashcard"
            >
              {createFlashcardMutation.isPending ? (
                <Loader2 className="h-4 w-4 mr-2 animate-spin" />
              ) : (
                <BookOpen className="h-4 w-4 mr-2" />
              )}
              Create Flashcard
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      <Dialog open={showQuizDialog} onOpenChange={setShowQuizDialog}>
        <DialogContent className="max-w-lg">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <HelpCircle className="h-5 w-5 text-fuchsia-600" />
              Create Quiz Question from Note
            </DialogTitle>
            <DialogDescription>
              Turn your note content into a quiz question and add it to an existing quiz.
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4 py-4">
            <div className="space-y-2">
              <label className="text-sm font-medium">Select Quiz</label>
              <select
                value={selectedQuizId}
                onChange={(e) => setSelectedQuizId(e.target.value)}
                className="w-full h-10 px-3 rounded-md border border-input bg-background text-sm"
                data-testid="select-quiz"
              >
                <option value="">Choose a quiz...</option>
                {quizzes.map((quiz) => (
                  <option key={quiz.id} value={quiz.id}>{quiz.title}</option>
                ))}
              </select>
              {quizzes.length === 0 && (
                <p className="text-xs text-muted-foreground">No quizzes available. Create a quiz first in the Quizzes section.</p>
              )}
            </div>
            <div className="space-y-2">
              <label className="text-sm font-medium">Question</label>
              <Textarea
                value={quizQuestion}
                onChange={(e) => setQuizQuestion(e.target.value)}
                placeholder="Enter your question..."
                className="min-h-[80px]"
                data-testid="input-quiz-question"
              />
            </div>
            <div className="space-y-2">
              <label className="text-sm font-medium">Options (mark the correct one)</label>
              {quizOptions.map((option, index) => (
                <div key={index} className="flex items-center gap-2">
                  <input
                    type="radio"
                    name="correctOption"
                    checked={correctOptionIndex === index}
                    onChange={() => setCorrectOptionIndex(index)}
                    className="h-4 w-4 accent-fuchsia-600"
                  />
                  <Input
                    value={option}
                    onChange={(e) => {
                      const newOptions = [...quizOptions];
                      newOptions[index] = e.target.value;
                      setQuizOptions(newOptions);
                    }}
                    placeholder={`Option ${index + 1}`}
                    data-testid={`input-quiz-option-${index}`}
                  />
                </div>
              ))}
            </div>
            <div className="space-y-2">
              <label className="text-sm font-medium">Explanation (optional)</label>
              <Textarea
                value={quizExplanation}
                onChange={(e) => setQuizExplanation(e.target.value)}
                placeholder="Explain the correct answer..."
                className="min-h-[60px]"
                data-testid="input-quiz-explanation"
              />
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowQuizDialog(false)}>
              Cancel
            </Button>
            <Button
              onClick={() => {
                const formattedOptions = quizOptions
                  .map((text, idx) => ({
                    text: text.trim(),
                    isCorrect: idx === correctOptionIndex,
                  }))
                  .filter(opt => opt.text);
                createQuizQuestionMutation.mutate({
                  quizId: selectedQuizId,
                  question: quizQuestion,
                  options: formattedOptions,
                  explanation: quizExplanation,
                });
              }}
              disabled={!selectedQuizId || !quizQuestion.trim() || quizOptions.filter(o => o.trim()).length < 2 || !quizOptions[correctOptionIndex]?.trim() || createQuizQuestionMutation.isPending}
              className="bg-fuchsia-600 hover:bg-fuchsia-700"
              data-testid="button-confirm-create-quiz"
            >
              {createQuizQuestionMutation.isPending ? (
                <Loader2 className="h-4 w-4 mr-2 animate-spin" />
              ) : (
                <HelpCircle className="h-4 w-4 mr-2" />
              )}
              Add Question
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Auto-Generate Dialog */}
      <Dialog open={showAutoGenerateDialog} onOpenChange={setShowAutoGenerateDialog}>
        <DialogContent className="max-w-md">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              {autoGenerateType === "quiz" ? (
                <>
                  <ListChecks className="h-5 w-5 text-teal-600" />
                  Generate Quiz from Note
                </>
              ) : (
                <>
                  <Zap className="h-5 w-5 text-cyan-600" />
                  Generate Flashcards from Note
                </>
              )}
            </DialogTitle>
            <DialogDescription>
              {autoGenerateType === "quiz"
                ? "Automatically create quiz questions from your note content. Questions will be generated based on key concepts."
                : "Automatically create flashcards from your note content. Each significant section becomes a flashcard."}
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4 py-4">
            {autoGenerateType === "flashcards" && (
              <div className="space-y-2">
                <label className="text-sm font-medium">Select Target Deck</label>
                <Select value={selectedDeckId} onValueChange={setSelectedDeckId}>
                  <SelectTrigger data-testid="select-auto-generate-deck">
                    <SelectValue placeholder="Choose a deck..." />
                  </SelectTrigger>
                  <SelectContent>
                    {decks.map((deck) => (
                      <SelectItem key={deck.id} value={deck.id}>{deck.title}</SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
            )}
            <div className="bg-slate-50 dark:bg-slate-800 rounded-lg p-4">
              <h4 className="font-medium text-sm mb-2">What will be generated:</h4>
              <ul className="text-sm text-muted-foreground space-y-1">
                {autoGenerateType === "quiz" ? (
                  <>
                    <li>Up to 5 questions from your note content</li>
                    <li>Questions based on concepts, definitions, and processes</li>
                    <li>Exam prompts get priority treatment</li>
                  </>
                ) : (
                  <>
                    <li>One flashcard per significant content block</li>
                    <li>Front: Question based on content type</li>
                    <li>Back: Full content from your notes</li>
                  </>
                )}
              </ul>
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowAutoGenerateDialog(false)}>
              Cancel
            </Button>
            <Button
              onClick={handleAutoGenerate}
              disabled={isGenerating || (autoGenerateType === "flashcards" && !selectedDeckId)}
              className={autoGenerateType === "quiz" 
                ? "bg-teal-600 hover:bg-teal-700" 
                : "bg-cyan-600 hover:bg-cyan-700"}
              data-testid="button-confirm-auto-generate"
            >
              {isGenerating ? (
                <Loader2 className="h-4 w-4 mr-2 animate-spin" />
              ) : autoGenerateType === "quiz" ? (
                <ListChecks className="h-4 w-4 mr-2" />
              ) : (
                <Zap className="h-4 w-4 mr-2" />
              )}
              {isGenerating ? "Generating..." : `Generate ${autoGenerateType === "quiz" ? "Quiz" : "Flashcards"}`}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
